# Server
server.port=8080

# Database ? apna MySQL username/password daal
spring.datasource.url=jdbc:mysql://localhost:3306/zivara_db
spring.datasource.username=root
spring.datasource.password=user1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret - koi bhi random string
jwt.secret=zivara_super_secret_key_2026_make_it_long
jwt.expiration=604800000

# File upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harpreetsingh27619@gmail.com
spring.mail.password=urbk gcea bwte pkmo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# OTP expire time - 5 minutes
otp.expiration.minutes=5